# Generated by Django 4.2 on 2023-08-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "username",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(default=0, max_length=20)),
                ("pwd", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=20)),
                ("authority", models.PositiveSmallIntegerField(default=0)),
                ("total_point", models.FloatField(default=0)),
                ("upload_post", models.PositiveIntegerField(default=0)),
                ("labeling_post", models.PositiveIntegerField(default=0)),
                ("question_post", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "UserInfo",
            },
        ),
    ]
