# app.yaml

runtime: python310
entrypoint: gunicorn -b :$PORT main.wsgi

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  max_instances: 10
  min_instances: 1
  min_idle_instances: 1

handlers:
- url: /static
  static_dir: main/staticfiles
- url: /.*
  script: auto
