# Generated by Django 4.2 on 2023-08-08 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("adminpage", "0001_initial"),
        ("Account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenerateId",
            fields=[
                (
                    "ginseng_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "username",
                    models.ForeignKey(
                        db_column="username",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Account.userinfo",
                    ),
                ),
            ],
            options={
                "db_table": "generate_ID",
            },
        ),
        migrations.CreateModel(
            name="WonsiBoard",
            fields=[
                ("wonsi_num", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("date", models.DateField(auto_now_add=True)),
                ("state", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "db_table": "wonsi_board",
            },
        ),
        migrations.CreateModel(
            name="WonsiData",
            fields=[
                (
                    "image_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("age", models.CharField(default=0, max_length=10)),
                ("grade", models.CharField(default=0, max_length=10)),
                ("variety", models.CharField(default=0, max_length=10)),
                ("wonsi_verification", models.SmallIntegerField(default=0)),
                (
                    "ginseng_id",
                    models.ForeignKey(
                        db_column="ginseng_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uploadpage.generateid",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        db_column="username",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Account.userinfo",
                    ),
                ),
            ],
            options={
                "db_table": "wonsi_data",
            },
        ),
        migrations.CreateModel(
            name="WonsiComments",
            fields=[
                (
                    "wonsi_comments_num",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("text", models.TextField()),
                ("create_date", models.DateField(auto_now_add=True)),
                (
                    "admin_id",
                    models.ForeignKey(
                        db_column="admin_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminpage.admin",
                    ),
                ),
                (
                    "wonsi_num",
                    models.ForeignKey(
                        db_column="wonsi_num",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uploadpage.wonsiboard",
                    ),
                ),
            ],
            options={
                "db_table": "wonsi_comments",
            },
        ),
        migrations.AddField(
            model_name="wonsiboard",
            name="image_id",
            field=models.ForeignKey(
                db_column="image_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="uploadpage.wonsidata",
            ),
        ),
        migrations.AddField(
            model_name="wonsiboard",
            name="username",
            field=models.ForeignKey(
                db_column="username",
                on_delete=django.db.models.deletion.CASCADE,
                to="Account.userinfo",
            ),
        ),
    ]
