# Generated by Django 4.2 on 2023-08-08 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("uploadpage", "0001_initial"),
        ("adminpage", "0001_initial"),
        ("Account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabelingBoard",
            fields=[
                ("board_num", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("create_date", models.DateField(auto_now_add=True)),
                ("state", models.PositiveIntegerField()),
            ],
            options={
                "db_table": "labeling_board",
            },
        ),
        migrations.CreateModel(
            name="LabelingWork",
            fields=[
                ("work_num", models.AutoField(primary_key=True, serialize=False)),
                ("label_verification", models.PositiveIntegerField()),
                (
                    "image_id",
                    models.ForeignKey(
                        db_column="image_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uploadpage.wonsidata",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        db_column="username",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Account.userinfo",
                    ),
                ),
            ],
            options={
                "db_table": "labeling_work",
            },
        ),
        migrations.CreateModel(
            name="LabelingData",
            fields=[
                ("label_num", models.AutoField(primary_key=True, serialize=False)),
                (
                    "head",
                    models.CharField(default="[0, 0, 0, 0]", max_length=50, null=True),
                ),
                (
                    "body",
                    models.CharField(default="[0, 0, 0, 0]", max_length=50, null=True),
                ),
                (
                    "leg",
                    models.CharField(default="[0, 0, 0, 0]", max_length=50, null=True),
                ),
                (
                    "total",
                    models.CharField(default="[0, 0, 0, 0]", max_length=50, null=True),
                ),
                ("label_verification", models.PositiveIntegerField()),
                (
                    "image_id",
                    models.ForeignKey(
                        db_column="image_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uploadpage.wonsidata",
                    ),
                ),
            ],
            options={
                "db_table": "labeling_data",
            },
        ),
        migrations.CreateModel(
            name="LabelingComments",
            fields=[
                (
                    "labeling_comments_num",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("text", models.TextField()),
                ("create_date", models.DateField(auto_now_add=True)),
                (
                    "admin_id",
                    models.ForeignKey(
                        db_column="admin_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminpage.admin",
                    ),
                ),
                (
                    "board_num",
                    models.ForeignKey(
                        db_column="board_num",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="labelingpage.labelingboard",
                    ),
                ),
            ],
            options={
                "db_table": "labeling_comments",
            },
        ),
        migrations.AddField(
            model_name="labelingboard",
            name="work_num",
            field=models.ForeignKey(
                db_column="work_num",
                on_delete=django.db.models.deletion.CASCADE,
                to="labelingpage.labelingwork",
            ),
        ),
    ]
